### ISSUE TITLE
Unable to Connect - Example sketch on Yún

### ISSUE THREAD

**Issue by robertcedwards** [julioterra/yunSpacebrew#2]
Using the example sketch provided…
Serial monitor is displaying the following:

``` bash
Unable to connect: retrying (1)... 
Unable to connect: retrying (2)... 
Unable to connect: retrying (3)... 
Unable to connect: retrying (4)... 
Unable to connect: is the sketch using the bridge?
```

I've setup my Yún and it's connected to the internet via Wifi…
Do I need to setup an instance of SpaceBrew on my local machine or a server in order to get this demo up and running?

**Comment by ghost** [comment]
That's because your are uploading the sketch using the LAN method and the serial monitor is showing the Console output. Try to upload the sketch using USB serial and then open serial monitor. Examples have a line like this:

```
while(!Serial){}
```

The sketch will not run until serial monitor is opened.

**Comment by julioterra** [comment]
Robert, sorry I missed the notification for your issue. Breaking labs is right, thanks for replying. If you want the Sketch to run without opening the serial monitor, then just remove

```
 while(!Serial){}
```

**Comment by robertcedwards** [comment]
Ah, I see…thanks! @julioterra & @breakinglabs
