### ISSUE TITLE
Abstract Spacebrew and Console away from websockets

### ISSUE THREAD

**Issue by chriddyp** [julioterra/yunSpacebrew#4]
The pubsub model that you have for `Spacebrew` is awesome. If it was abstracted away from websockets, than it could be the default synchronous communication layer between  Arduino and Python programs written on the Linino. The `Mailbox` could remain the asynchronous layer.

In Python, users could just subscribe event handlers, just as you've done internally

```
sb = Spacebrew()
sb.on_message = on_message
def on_message(message):
    pass
```

This would address some of the concerns listed in the forums:
[Two way information in Python Script](http://forum.arduino.cc/index.php/topic,207380.0.html)
[Yun transfer rate very slow](http://forum.arduino.cc/index.php/topic,191628.0.html)

I'm writing the Yún client for [Plotly's](https://plot.ly) streaming API (examples here: [https://github.com/plotly/streaming-demos](https://github.com/plotly/streaming-demos)) and I'll probably end up doing this abstraction.

I'm happy to submit a PR back to `yunSpacebrew` if this makes sense to you!

Thanks a bunch for writing this library!

**Comment by julioterra** [comment]
Quin, happy to hear that my work my have legs beyond my original creation. I would love to talk to you more about this, so that I can better understand your vision. Let's try to touch base this week or weekend.

Julio

**Comment by chriddyp** [comment]
I ended up writing this in its own repository. A library called YunMessenger ( [https://github.com/plotly/YunMessenger](https://github.com/plotly/YunMessenger) ), to make communication between the two processors easier. Thanks for the help!
